### ISSUE TITLE
Audio is working but no headphones/speakers switch

### ISSUE THREAD

**Issue by lonewsk** [css459/arch-linux-arm-clockworkpi-a06#2]
Audio is working out-of-the-box but is playing on both speakers and headphones. No Auto-Mute option on alsa sound card. No difference between pulseaudio and pipewire.

Output of aplay -l
`**** List of PLAYBACK Hardware Devices ****
card 0: rockchipes8388c [rockchip,es8388-codec], device 0: ff880000.i2s-es8328-hifi-analog es8328-hifi-analog-0 [ff880000.i2s-es8328-hifi-analog es8328-hifi-analog-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: hdmisound [hdmi-sound], device 0: ff8a0000.i2s-i2s-hifi i2s-hifi-0 [ff8a0000.i2s-i2s-hifi i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

Is it kernel-related?

**Comment by lonewsk** [comment]
alsactl init ouputs
`alsactl init
alsa-lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
Found hardware: "simple-card" "" "" "" ""
Hardware is initialized using a generic method
alsa-lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2
Found hardware: "simple-card" "" "" "" ""
Hardware is initialized using a generic method`

**Comment by css459** [comment]
Hey thanks for raising this and the PR. I believe the Manjaro folks might be trying to fix something with the audio as well. If it’s kernel related, that would be an easy fix here since we use their kernel with some minor changes. My speakers are likely broken so it will be more difficult for me to test.
